### ISSUE TITLE
Interpretation of results

### ISSUE THREAD

**Issue by WhaleGe** [Fraternalilab/sciCSR#5]
Hello, after solving many problems, I finally ran through your process on my own data set and got some results. But I have some doubts about the results. I found that the score of NR flowing to A1 is higher, but in the end the stationary distribution shows that the proportion of R in A1 is higher. What do you think of this issue?

![image](https://github.com/Fraternalilab/sciCSR/assets/32753674/04168165-e5f4-411c-b30a-a91328628dd3)
![image](https://github.com/Fraternalilab/sciCSR/assets/32753674/154cf425-dfb7-4cc5-924a-2a32fdbb6f50)

**Comment by josef0731** [comment]
Hi,

* The stationary distribution describes the distribution of states "at equilibrium". In our experience we find that tends to match the observed distribution of states (in the data used to fit the model) quite well.
* The flux on the other hand measures transitions between states. In a system with good amount of signals of transition (see below) we find you can use these fluxes to estimate *prospectively* (ie at a future timepoint) the state distribution - this was what we did in the paper for the SARS-CoV-2 vaccination data (Fig 5).
* In our experimentation we did find occasions where we don't observe a good amount of signals for transitions - the flux plot would look very empty (you would only see one dot from the start to the end state, and nothing else). Looking at your first plot I would say this is the case. 
 
If I were you I would also take a look at the flux plot for your other state - happy to take this discussion offline if you wish.

**Comment by josef0731** [comment]
I will close this issue, but if there are anything I can help, please open a new issue.
